# Generated by Django 4.2.6 on 2023-12-21 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='expense_type',
            field=models.CharField(choices=[('Positive', 'Credit'), ('Negative', 'Debit')], default='Debit', max_length=10),
        ),
    ]
