# Generated by Django 4.2.6 on 2023-12-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_alter_transaction_options_transaction_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.FloatField(default=models.FloatField(default=0)),
        ),
    ]
